import Head from "next/head";
import GlobalLayout from "@/components/layout";
import "@/styles/globals.css";
import { ConfigProvider, theme } from "antd";

const { darkAlgorithm } = theme;

export default function App({ Component, pageProps }) { 
  return <>
    <Head>
      <title>HEIC to JPG Free Converter</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <ConfigProvider
      theme={{
        // algorithm:  darkAlgorithm, // Dark mode için
        token: {
          // colorBgContainer: '#0f1923',
        },
        components: {
          Menu: {
            // colorBgContainer: '#10162a',
          },
          Layout: {
            // colorBgContainer: '#10162a',
            headerBg: '#fff'
          }
        },
      }}
    >
      <GlobalLayout>
        <Component {...pageProps} />
      </GlobalLayout>
    </ConfigProvider>
  </>;
}
